services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: mern-backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - mern-network

  frontend:
    build: ./client
    container_name: mern-frontend
    ports:
      - "8080:4173"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
